language: php

php:
    - 7.2
    - 7.3
    - 7.4

stages:
    - Code Checks
    - test

services: mysql

before_install: mv tests/local.travis.neon app/config/local.neon

install: composer install --no-interaction --prefer-source

before_script:
    - mysql -u root -e 'CREATE DATABASE test;'
    - php bin/console orm:schema-tool:create
    - php bin/console dbal:import fixtures.sql

script: composer tester

after_failure:
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

jobs:
    include:
        -   stage: Code Checks
            name: Static Analysis
            php: 7.4
            before_install: ~
            before_script: ~
            script: composer phpstan

        -   stage: Code Checks
            name: Code Checker
            php: 7.4
            before_install: ~
            before_script: ~
            script: composer code-checker

        -   stage: Code Checks
            name: Entity Annotations Validation
            php: 7.4
            before_script: ~
            script: composer schema
